include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "plugins/**"
  errors:
    invalid_annotation_target: ignore
    unused_element: ignore
  plugins:
    - custom_lint